// MISC app actions
export const LANG_RESOURCE_ACTION = 'LANG_RESOURCE_ACTION';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Account actions
export const ADD_ACCOUNT_SUCCESS = "ADD_ACCOUNT_SUCCESS";
export const ADD_ACCOUNT_FAILURE = "ADD_ACCOUNT_FAILURE";
export const GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_ACTION_SUCCESS";
export const GET_ACCOUNTS_FAILURE = "GET_ACCOUNTS_ACTION_FAILURE";

// Pilot related actions
export const ADD_PILOT_SUCCESS = "ADD_PILOT_SUCCESS";
export const ADD_PILOT_FAILURE = "ADD_PILOT_FAILURE";
export const GET_PILOTS_SUCCESS = "GET_PILOTS_ACTION_SUCCESS";
export const GET_PILOTS_FAILURE = "GET_PILOTS_ACTION_FAILURE";

export const DUMMY_ACTION = "DUMMY_ACTION";
export const DUMMY_FAILED = "DUMMY_FAILED";