export const LANG_RESOURCE_ACTION = 'LANG_RESOURCE_ACTION';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const GET_ACCOUNTS_ACTION_SUCCESS = "GET_ACCOUNTS_ACTION_SUCCESS";
export const GET_ACCOUNTS_ACTION_FAILURE = "GET_ACCOUNTS_ACTION_FAILURE";

export const GET_PILOTS_ACTION_SUCCESS = "GET_PILOTS_ACTION_SUCCESS";
export const GET_PILOTS_ACTION_FAILURE = "GET_PILOTS_ACTION_FAILURE";

export const DUMMY_ACTION = "DUMMY_ACTION";
export const DUMMY_FAILED = "DUMMY_FAILED";