// MISC app actions
export const LANG_RESOURCE_ACTION = 'LANG_RESOURCE_ACTION';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Account actions
export const ADD_ACCOUNT_SUCCESS = "ADD_ACCOUNT_SUCCESS";
export const ADD_ACCOUNT_FAILURE = "ADD_ACCOUNT_FAILURE";
export const GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_SUCCESS";
export const GET_ACCOUNTS_FAILURE = "GET_ACCOUNTS_FAILURE";

// Character related actions
//export const ADD_CHARACTER = "ADD_CHARACTER";
export const ADD_CHARACTER_SUCCESS = "ADD_CHARACTER_SUCCESS";
export const ADD_CHARACTER_FAILURE = "ADD_CHARACTER_FAILURE";
export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const GET_CHARACTERS_FAILURE = "GET_CHARACTERS_FAILURE";
export const REMOVE_CHARACTER = "REMOVE_CHARACTER";
export const REMOVE_CHARACTER_SUCCESS = "REMOVE_CHARACTER_SUCCESS";
export const REMOVE_CHARACTER_FAILURE = "REMOVE_CHARACTER_FAILURE";

export const GET_FITTINGS_SUCCESS = "GET_FITTINGS_SUCCESS";
export const GET_FITTINGS_FAILURE = "GET_FITTINGS_FAILURE";

export const GET_SHOPPINGLISTS_SUCCESS = "GET_SHOPPINGLISTS_SUCCESS";
export const GET_SHOPPINGLISTS_FAILURE = "GET_SHOPPINGLISTS_FAILURE";

export const DUMMY_ACTION = "DUMMY_ACTION";
export const DUMMY_FAILED = "DUMMY_FAILED";