apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: everything-dev
  name: everything-dev
  namespace: everything-dev
spec:
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: '172.30.124.220:5000/openshift/dotnetsdk:latest'
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'everything-dev:latest'
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  triggers:
    - generic:
        secret: r-B5FqyBPkmiowAWbiFx
      type: Generic
  postCommit: {}
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
