kind: BuildConfig
apiVersion: v1
metadata:
  name: everything-ef-migration-dev
  labels:
    app: everything-ef-migration-dev
  namespace: everything-dev
spec:
  runPolicy: Serial
  strategy:
    dockerStrategy:
      kind: DockerImage
      name: mcr.microsoft.com/dotnet/core/sdk
  source:
    type: Binary
    binary: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'everything-ef-migration-dev:latest'
    