kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: mysql-data-claim
spec:
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 1Gi
 storageClassName: local-storage
 selector:
  name: mysql-data