apiVersion: v1
kind: PersistentVolume
metadata:
  name: svak-volume1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  persistentVolumeReclaimPolicy: Recycle
  hostPath: 
    path: /var/lib/minishift/base/openshift.local.pv/svak-volume1
