apiVersion: v1
kind: Service
metadata:
  labels:
    app: everything-dev
  name: everything-dev
  namespace: everything-dev
spec:
  clusterIP: 172.30.44.172
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: everything-dev
    deploymentconfig: everything-dev
  sessionAffinity: None
  type: ClusterIP
  