FROM microsoft/dotnet:sdk as build-env
WORKDIR /app

COPY EVErything.Web/EVErything.Web.csproj ./EVErything.Web/
COPY EVErything.Business/EVErything.Business.csproj ./EVErything.Business/
RUN dotnet restore EVErything.Web/EVErything.Web.csproj

COPY ./EVErything.Web/. ./EVErything.Web/
COPY ./EVErything.Business/. ./EVErything.Business/

RUN dotnet publish -c Debug -f netcoreapp2.2 -o /app/publish EVErything.Web/EVErything.Web.csproj

FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/publish .
ENTRYPOINT ["dotnet", "EVErything.Web.dll"]